models/Barang.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\behaviors\BlameableBehavior;
use app\models\Kantor;
use yii\helpers\ArrayHelper;
/**
 * This is the model class for table "barang".
 *
 * @property integer $id
 * @property string $kode
 * @property string $gambar
 * @property string $nama
 * @property string $deskripsi
 * @property double $mlat
 * @property double $mlong
 * @property integer $jumlah
 * @property integer $id_kantor
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 */
class Barang extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'barang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['kode', 'nama', 'deskripsi','id_kantor'], 'required'],
        	['kode', 'unique', 'targetAttribute' => 'kode'],
            [['deskripsi'], 'string'],
            //[['mlat', 'mlong'], 'number'],
       		[['mlat', 'mlong'], 'string', 'max' => 25],
            [['jumlah', 'id_kantor', 'created_by', 'updated_by'], 'integer'],
       		[['jumlah'],'default','value'=>'0'],
            [['created_at', 'updated_at'], 'safe'],
            [['kode', 'nama'], 'string', 'max' => 20],
            //[['gambar'], 'string', 'max' => 200]
        	['gambar', 'file', 'extensions' => ['png', 'jpg', 'gif'], 'maxSize' => 512000, 'tooBig' => 'batas 500KB'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'kode' => 'Kode',
            'gambar' => 'Gambar',
            'nama' => 'Nama',
            'deskripsi' => 'Deskripsi',
            'mlat' => 'Mlat',
            'mlong' => 'Mlong',
            'jumlah' => 'Jumlah',
            'id_kantor' => 'Id Kantor',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }
    
    //webservice purpose, override
    public function fields(){
    	return ['kode', 'nama', 'id_kantor'];
    }
    
    public function getKantor()
    {
    	return $this->hasOne(Kantor::className(), ['id' => 'id_kantor']);
    }
    
    public function getCreator(){
    	return $this->hasOne(User::className(), ['id' => 'created_by']);
    }
    
    public function getUpdator(){
    	return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }
    
    public function behaviors()
    {	
    	
    	return [
    			'timestamp' => [
    					'class' => 'yii\behaviors\TimestampBehavior',
    					'attributes' => [
    							ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
    							ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
    					],
    					'value' => new Expression('NOW()'),
    			],
    			[
	    			'class' => BlameableBehavior::className(),
	    			'createdByAttribute' => 'created_by',
	    			'updatedByAttribute' => 'updated_by',
    			],
    	];
    }
    
    /*
	public function beforeSave() {
		//trik, $this->isNewRecord
		
		var_dump($this->jumlah);
		var_dump(is_int($this->jumlah));
		die();
		if(!is_int($this->jumlah)){$this->jumlah =0; }		
		
		return true;
	}*/
	
	public static function getKantorList()
	{
		$droptions = Kantor::find()->asArray()->all();
		return Arrayhelper::map($droptions, 'id', 'nama');
	}
}

controllers/BarangController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Barang;
use app\models\BarangSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\data\Pagination;
use app\models\Validasi;
use kartik\mpdf\Pdf;

/**
 * BarangController implements the CRUD actions for Barang model.
 */
class BarangController extends Controller
{
    public function behaviors()
    {
        return [
        	//level kontrol
        	'access' => [
        				'class' => \yii\filters\AccessControl::className(),
        				//'only' => ['index', 'view','create', 'update', 'delete'],
        				'rules' => [
        						[
        								'actions' => ['index', 'view',],
        								'allow' => true,
        								'roles' => ['?'],
        						],
        		
        						[
        								'actions' => ['index', 'view','chart',
        										'lihat','cetakpdf','export'],
        								'allow' => true,
        								'roles' => ['@'],
        						],
        						[
        								'actions' => ['create'],
        								'allow' => true,
        								'roles' => ['@'],
        								'matchCallback' => function ($rule, $action) {
        										//return true;
        										return Validasi::cekRole('Admin') || Validasi::cekRole('Customer service');
        								}
        						],
        						[
        								'actions' => ['update', 'delete'],
        								'allow' => true,
        								'roles' => ['@'],
        								'matchCallback' => function ($rule, $action) {
        								//return true;
        								return Validasi::cekRole('Admin');
        									}
        						],
        						
        						//hanya yg buat boleh update/delete
        						[
        								'actions' => ['update','delete'],
        								'class' => 'app\filters\BarangRule',
        						],
        		
        					],
        				],
        		      	//	
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Barang models.
     * @return mixed
     */
    public function actionIndex()
    {	
        $searchModel = new BarangSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    //kustom
    public function actionLihat(){
    	$query = Barang::find();
    	
    	$countQuery = clone $query;
    	 
    	$pages = new Pagination(['totalCount' => $countQuery->count()]);
    	$pages->pageSize =2;
    	
    	$models = $query
    	->offset($pages->offset)
    	->limit($pages->limit) 
    	//->where(['kode' => 'x5',])
    	->all();
    	
    	return $this->render('lihat', [    			
    			'dataProvider' => $models,
    			'pages' => $pages,
    	]);
    }
    
    public function actionChart(){
    	$query = Barang::find();
    	  
    	$models = $query->andFilterWhere(['>=', 'jumlah', 0])->all();
    	
    	return $this->render('chart',['dataProvider' => $models]);
    }

    /**
     * Displays a single Barang model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    
    //kustom
    public function actionCetakpdf($id){
    	// get your HTML raw content without any layouts or scripts
    	//$content = $this->renderPartial('_reportView');
    	$content = $this->renderPartial('cetak',[
            'model' => $this->findModel($id),
        ]);
    	
    	// setup kartik\mpdf\Pdf component
    	$pdf = new Pdf([
    			// set to use core fonts only
    			'mode' => Pdf::MODE_CORE,
    			// A4 paper format
    			'format' => Pdf::FORMAT_A4,
    			// portrait orientation
    			'orientation' => Pdf::ORIENT_PORTRAIT,
    			// stream to browser inline
    			'destination' => Pdf::DEST_BROWSER,
    			// your html content input
    			'content' => $content,
    			// format content from your own css file if needed or use the
    			// enhanced bootstrap css built by Krajee for mPDF formatting
    			'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
    			// any css to be embedded if required
    			'cssInline' => '.kv-heading-1{font-size:18px}',
    			// set mPDF properties on the fly
    			'options' => ['title' => $this->findModel($id)->kode],
    			// call mPDF methods on the fly
    			'methods' => [
    					'SetHeader'=>[$this->findModel($id)->kode],
    					'SetFooter'=>['{PAGENO}'],
    			]
    	]);
    	
    	// return the pdf output as per the destination setting
    	return $pdf->render();
    }
    
    public function actionExport(){
    	$searchModel = new BarangSearch();
    	$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    	
    	return $this->render('export', [
    			'searchModel' => $searchModel,
    			'dataProvider' => $dataProvider,
    	]);
    }

    /**
     * Creates a new Barang model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {	
        $model = new Barang();

        if ($model->load(Yii::$app->request->post())) {
        	        	
        	$model->gambar = UploadedFile::getInstance($model, 'gambar');
        	 
        	if(!$model->gambar==NULL){
        		//save file
        		$unik = $model->kode;
        		$namafile = $model->gambar->baseName.$unik;
        		$extensi = $model->gambar->extension;
        		
        		$model->gambar->saveAs('uploads/'.$namafile.'.'.$extensi);
        		$model->gambar = 'uploads/'.$namafile.'.'.$extensi;
        	}
        	
        	$model->save();
        	
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    

    /**
     * Updates an existing Barang model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $tmpgambar = $model->gambar;

        if ($model->load(Yii::$app->request->post())) {
        	
        	$model->gambar = UploadedFile::getInstance($model, 'gambar');
        	
        	if(!$model->gambar==NULL){
        		//save file
        		$unik = $model->kode;
        		$namafile = $model->gambar->baseName.$unik;
        		$extensi = $model->gambar->extension;
        	
        		$model->gambar->saveAs('uploads/'.$namafile.'.'.$extensi);
        		$model->gambar = 'uploads/'.$namafile.'.'.$extensi;
        	} else {
        		if($tmpgambar!=NULL) $model->gambar = $tmpgambar;
        	}
        	$model->save();
        	
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Barang model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
    	$tmpfilepath = $this->findModel($id)->gambar;
    	 
    	if($tmpfilepath!=NULL || $tmpfilepath!='')
    		if(is_file($this->findModel($id)->gambar)) unlink($this->findModel($id)->gambar);
    	
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
        
    }

    /**
     * Finds the Barang model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Barang the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Barang::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/barang/Copy_2_of_export.php
<?php 
use kartik\export\ExportMenu;

$defaultExportConfig = [
		\kartik\grid\GridView::HTML => [
				'label' => Yii::t('kvgrid', 'HTML'),
				'icon' => $isFa ? 'file-text' : 'floppy-saved',
				'iconOptions' => ['class' => 'text-info'],
				'showHeader' => true,
				'showPageSummary' => true,
				'showFooter' => true,
				'showCaption' => true,
				'filename' => Yii::t('kvgrid', 'grid-export'),
				'alertMsg' => Yii::t('kvgrid', 'The HTML export file will be generated for download.'),
				'options' => ['title' => Yii::t('kvgrid', 'Hyper Text Markup Language')],
				'mime' => 'text/html',
				'config' => [
						'cssFile' => 'http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css'
				]
		],
		\kartik\grid\GridView::CSV => [
				'label' => Yii::t('kvgrid', 'CSV'),
				'icon' => $isFa ? 'file-code-o' : 'floppy-open',
				'iconOptions' => ['class' => 'text-primary'],
				'showHeader' => true,
				'showPageSummary' => true,
				'showFooter' => true,
				'showCaption' => true,
				'filename' => Yii::t('kvgrid', 'grid-export'),
				'alertMsg' => Yii::t('kvgrid', 'The CSV export file will be generated for download.'),
				'options' => ['title' => Yii::t('kvgrid', 'Comma Separated Values')],
				'mime' => 'application/csv',
				'config' => [
						'colDelimiter' => ",",
						'rowDelimiter' => "\r\n",
				]
		],
		\kartik\grid\GridView::TEXT => [
				'label' => Yii::t('kvgrid', 'Text'),
				'icon' => $isFa ? 'file-text-o' : 'floppy-save',
				'iconOptions' => ['class' => 'text-muted'],
				'showHeader' => true,
				'showPageSummary' => true,
				'showFooter' => true,
				'showCaption' => true,
				'filename' => Yii::t('kvgrid', 'grid-export'),
				'alertMsg' => Yii::t('kvgrid', 'The TEXT export file will be generated for download.'),
				'options' => ['title' => Yii::t('kvgrid', 'Tab Delimited Text')],
				'mime' => 'text/plain',
				'config' => [
						'colDelimiter' => "\t",
						'rowDelimiter' => "\r\n",
				]
		],
		\kartik\grid\GridView::EXCEL => [
				'label' => Yii::t('kvgrid', 'Excel'),
				'icon' => $isFa ? 'file-excel-o' : 'floppy-remove',
				'iconOptions' => ['class' => 'text-success'],
				'showHeader' => true,
				'showPageSummary' => true,
				'showFooter' => true,
				'showCaption' => true,
				'filename' => Yii::t('kvgrid', 'grid-export'),
				'alertMsg' => Yii::t('kvgrid', 'The EXCEL export file will be generated for download.'),
				'options' => ['title' => Yii::t('kvgrid', 'Microsoft Excel 95+')],
				'mime' => 'application/vnd.ms-excel',
				'config' => [
						'worksheet' => Yii::t('kvgrid', 'ExportWorksheet'),
						'cssFile' => ''
				]
		],
		\kartik\grid\GridView::PDF => [
				'label' => Yii::t('kvgrid', 'PDF'),
				'icon' => $isFa ? 'file-pdf-o' : 'floppy-disk',
				'iconOptions' => ['class' => 'text-danger'],
				'showHeader' => true,
				'showPageSummary' => true,
				'showFooter' => true,
				'showCaption' => true,
				'filename' => Yii::t('kvgrid', 'grid-export'),
				'alertMsg' => Yii::t('kvgrid', 'The PDF export file will be generated for download.'),
				'options' => ['title' => Yii::t('kvgrid', 'Portable Document Format')],
				'mime' => 'application/pdf',
				'config' => [
						'mode' => 'c',
						'format' => 'A4-L',
						'destination' => 'D',
						'marginTop' => 20,
						'marginBottom' => 20,
						'cssInline' => '.kv-wrap{padding:20px;}' .
						'.kv-align-center{text-align:center;}' .
						'.kv-align-left{text-align:left;}' .
						'.kv-align-right{text-align:right;}' .
						'.kv-align-top{vertical-align:top!important;}' .
						'.kv-align-bottom{vertical-align:bottom!important;}' .
						'.kv-align-middle{vertical-align:middle!important;}' .
						'.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
						'.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
						'.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
						'methods' => [
								'SetHeader' => [
										['odd' => $pdfHeader, 'even' => $pdfHeader]
								],
								'SetFooter' => [
										['odd' => $pdfFooter, 'even' => $pdfFooter]
								],
						],
						'options' => [
								'title' => $title,
								'subject' => Yii::t('kvgrid', 'PDF export generated by kartik-v/yii2-grid extension'),
								'keywords' => Yii::t('kvgrid', 'krajee, grid, export, yii2-grid, pdf')
						],
						'contentBefore'=>'',
						'contentAfter'=>''
				]
		],
		\kartik\grid\GridView::JSON => [
				'label' => Yii::t('kvgrid', 'JSON'),
				'icon' => $isFa ? 'file-code-o' : 'floppy-open',
				'iconOptions' => ['class' => 'text-warning'],
				'showHeader' => true,
				'showPageSummary' => true,
				'showFooter' => true,
				'showCaption' => true,
				'filename' => Yii::t('kvgrid', 'grid-export'),
				'alertMsg' => Yii::t('kvgrid', 'The JSON export file will be generated for download.'),
				'options' => ['title' => Yii::t('kvgrid', 'JavaScript Object Notation')],
				'mime' => 'application/json',
				'config' => [
						'colHeads' => [],
						'slugColHeads' => false,
						'jsonReplacer' => null,
						'indentSpace' => 4
				]
		],
];

$gridColumns = [
    ['class' => 'yii\grid\SerialColumn'],
    'id',
    'kode',
    'nama',
    'jumlah',
    //['class' => 'yii\grid\ActionColumn'],
];

// Renders a export dropdown menu
echo ExportMenu::widget([
    'dataProvider' => $dataProvider,
    'columns' => $gridColumns,
	'export'=>'skip-export-pdf'
	
]);

// You can choose to render your own GridView separately

echo \kartik\grid\GridView::widget([
    'dataProvider' => $dataProvider,
    //'filterModel' => $searchModel,
    'columns' => $gridColumns,
		//$defaultExportConfig
		'exportConfig' => $defaultExportConfig
]);

views/barang/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\ckeditor\CKEditor;

/* @var $this yii\web\View */
/* @var $model app\models\Barang */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="barang-form">

    <?php $form = ActiveForm::begin(['options'=>['enctype'=>'multipart/form-data']]); ?>

    <?= $form->field($model, 'kode')->textInput(['maxlength' => true]) ?>
   
    <?= $form->field($model, 'gambar')->fileInput()->label('Gambar') ?>

    <?= $form->field($model, 'nama')->textInput(['maxlength' => true]) ?>  
    
	<?= $form->field($model, 'deskripsi')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'custom_v1'
    ]) ?>   
    

    <?= $form->field($model, 'mlat')->textInput(['readonly' => true]) ?>
	<?= $form->field($model, 'mlong')->textInput(['readonly' => true]) ?>
	
	 
	<?= \ibrarturi\latlngfinder\LatLngFinder::widget([
	    'model' => $model,              // model object
		'latAttribute' => 'mlat',        // Latitude attribute
		'lngAttribute' => 'mlong',        // Longitude attribute
		'defaultLat' => -6.938014486859704,        // Default latitude for the map
		'defaultLng' => 107.58636474609375,         // Default Longitude for the map
		'defaultZoom' => 8,             // Default zoom for the map
		'enableZoomField' => false,      // True: for assigning zoom values to the zoom field, False: Do not assign zoom value to the zoom field
	]); ?>

    <?= $form->field($model, 'jumlah')->textInput() ?>    
    
    <?= $form->field($model, 'id_kantor')->dropDownList($model->kantorList,
	[ 'prompt' => 'Pilih' ]);?>
    

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>


 




    <?php ActiveForm::end(); ?>

</div>

views/barang/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BarangSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="barang-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'kode') ?>

    <?= $form->field($model, 'gambar') ?>

    <?= $form->field($model, 'nama') ?>

    <?= $form->field($model, 'deskripsi') ?>

    <?php // echo $form->field($model, 'mlat') ?>

    <?php // echo $form->field($model, 'mlong') ?>

    <?php // echo $form->field($model, 'jumlah') ?>

    <?php // echo $form->field($model, 'id_kantor') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/barang/cetak.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;



/* @var $this yii\web\View */
/* @var $model app\models\Barang */

$this->title = $model->kode;
$this->params['breadcrumbs'][] = ['label' => 'Barangs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="barang-view">

    <h1><?= Html::encode($this->title) ?></h1>   
    LOGO LOGO 1818181818
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            'kode',
            //'gambar',
       		[
        		'attribute'=>'gambar',
        		'value'=>$model->gambar,
        		'format' => ['image',['width'=>'100','height'=>'100']],
       		],
            'nama',
            //'deskripsi:ntext',
       		[ 'attribute' => 'deskripsi','format' => 'html'],                  	
            'jumlah',
        	'kantor.nama',	
            'created_at',            
        	'creator.username',	
            'updated_at',            
       		'updator.username',
        ],
    ]) ?>
   hasilnya adalah rp 10000
</div>

views/barang/chart.php
<?php
use dosamigos\chartjs\ChartJs;


$this->title = 'Barang grafik';
$this->params['breadcrumbs'][] = $this->title;


foreach ($dataProvider as $x){
	$label[] =	$x->kode;
	$data[] =	$x->jumlah;	
}
?>

<?= ChartJs::widget([
    'type' => 'Line',
    'options' => [
        'height' => 400,
        'width' => 400
    ],
    'data' => [
        'labels' => $label,
        'datasets' => [
            [
                'fillColor' => "rgba(220,220,220,0.5)",
                'strokeColor' => "rgba(220,220,220,1)",
                'pointColor' => "rgba(220,220,220,1)",
                'pointStrokeColor' => "#fff",
                'data' => $data
            ],            
        ]
    ]
]);
?>

views/barang/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Barang */

$this->title = 'Create Barang';
$this->params['breadcrumbs'][] = ['label' => 'Barangs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="barang-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/barang/export.php
<?php 
use kartik\export\ExportMenu;

echo 'dsdsdsdsdsdssssssssssss';

$gridColumns = [
    ['class' => 'yii\grid\SerialColumn'],
    'id',
    'kode',
    'nama',
    'jumlah',
    //['class' => 'yii\grid\ActionColumn'],
];

// Renders a export dropdown menu
echo ExportMenu::widget([
    'dataProvider' => $dataProvider,
    'columns' => $gridColumns,
	'export'=>'skip-export-pdf'
	
]);

// You can choose to render your own GridView separately

echo \kartik\grid\GridView::widget([
    'dataProvider' => $dataProvider,
    //'filterModel' => $searchModel,
    'columns' => $gridColumns,
]);

views/barang/index.php
<?php

use yii\helpers\Html;
use yii\widgets\Pjax;
use yii\grid\GridView;
use app\models\Validasi;

/* @var $this yii\web\View */
/* @var $searchModel app\models\BarangSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


$this->title = 'Barangs';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="barang-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Barang', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'kode',
            //'gambar',
            'nama',
            //'deskripsi:ntext',
            // 'mlat',
            // 'mlong',
            'jumlah',        		
            // 'id_kantor',
            // 'created_at',
            // 'created_by',
            // 'updated_at',
            // 'updated_by',

            [
            		'class' => 'yii\grid\ActionColumn',
            		'template' => '{view} {update} {delete}',
            		'buttons' => [
            				'update' => function ($url, $model) {
	            				$isAdm = !Yii::$app->user->isGuest? (Validasi::cekRole('Admin')?true:false) : false;
	            				
	            				$isCreator = false;
	            				
	            				if($model->created_by!=null){	            					
	            					$isCreator = (Yii::$app->user->id == $model->created_by)? true: false;
            				}
            				 
            				if($isAdm || $isCreator)
            					return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['update', 'id' => $model['id']], [
            							'title' => Yii::t('yii', 'Update'),
            							'data-pjax' => '0',
            					]);
            				}
            				,
            				//delete
            				'delete' => function ($url, $model) {
	            				$isAdm = !Yii::$app->user->isGuest? (Validasi::cekRole('Admin')?true:false) : false;
	        
	            				$isCreator = false;
	        
	            				if($model->created_by!=null){
	            					$isCreator = (Yii::$app->user->id == $model->created_by)? true: false;
            				}
         
            				if($isAdm || $isCreator)
            					return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['delete', 'id' => $model['id']], [
            							'title' => Yii::t('yii', 'Delete'),
            							'data-pjax' => '0',
            					]);
            				}
            		]
        	],
        ],
    ]); ?>

</div>

views/barang/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Barang */

$this->title = 'Update Barang: ' . ' ' . $model->kode;
$this->params['breadcrumbs'][] = ['label' => 'Barangs', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->kode, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="barang-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>